### ISSUE TITLE
widget sufixes don't match the ones created by PLC vacuum lib

### ISSUE THREAD

**Issue by domitto** [pcdshub/pcdswidgets#19]
Hello,
It looks like the PV suffixes between plc lib and the widgets do not match.
I'm attaching the generated db file (from pytmc) and the connection list from the pydm screen.

[gmd.zip](https://github.com/pcdshub/pcdswidgets/files/3489382/gmd.zip)

Thanks,
Diego

**Comment by hhslepicka** [comment]
Thank you for reporting the issue, @domitto .
We are updating the suffixes on the widgets and a Pull Request will be out soon fixing the issue.

**Comment by domitto** [comment]
There's still a bunch of disconnected pvs, e.g.: :STATE_RBV does not exist in the IOC.
PYDM ca list:

ca://fb:EM1K0:GMD:VRC:10:OPN_SW
ca://fb:EM1K0:GMD:VRC:10:OPN_DI_RBV
ca://fb:EM1K0:GMD:VRC:10:CLS_DI_RBV
ca://fb:EM1K0:GMD:VRC:10:STATE_RBV
ca://fb:EM1K0:GMD:VRC:10:OPN_OK_RBV
ca://fb:EM1K0:GMD:GPI:10:PRESS_RBV
ca://fb:EM1K0:GMD:GPI:10:PRESS_OK_RBV
ca://fb:EM1K0:GMD:GCC:10:HV_SW
ca://fb:EM1K0:GMD:GCC:10:PRESS_RBV
ca://fb:EM1K0:GMD:GCC:10:STATE_RBV
ca://fb:EM1K0:GMD:GCC:10:ILK_OK_RBV
ca://fb:EM1K0:GMD:PTM:10:RUN_SW
ca://fb:EM1K0:GMD:PTM:10:STATE_RBV
ca://fb:EM1K0:GMD:PTM:10:FAULT_RBV
ca://fb:EM1K0:GMD:PTM:10:ILK_OK_RBV
ca://fb:EM1K0:GMD:VRC:20:OPN_SW
ca://fb:EM1K0:GMD:VRC:20:OPN_DI_RBV
ca://fb:EM1K0:GMD:VRC:20:CLS_DI_RBV
ca://fb:EM1K0:GMD:VRC:20:STATE_RBV
ca://fb:EM1K0:GMD:VRC:20:OPN_OK_RBV
ca://fb:EM1K0:GMD:GCC:20:HV_SW
ca://fb:EM1K0:GMD:GCC:20:PRESS_RBV
ca://fb:EM1K0:GMD:GCC:20:STATE_RBV
ca://fb:EM1K0:GMD:GCC:20:ILK_OK_RBV
ca://fb:EM1K0:GMD:PTM:20:RUN_SW
ca://fb:EM1K0:GMD:PTM:20:STATE_RBV
ca://fb:EM1K0:GMD:PTM:20:FAULT_RBV
ca://fb:EM1K0:GMD:PTM:20:ILK_OK_RBV
ca://fb:EM1K0:GMD:VRC:30:OPN_SW
ca://fb:EM1K0:GMD:VRC:30:OPN_DI_RBV
ca://fb:EM1K0:GMD:VRC:30:CLS_DI_RBV
ca://fb:EM1K0:GMD:VRC:30:STATE_RBV
ca://fb:EM1K0:GMD:VRC:30:OPN_OK_RBV
ca://fb:EM1K0:GMD:GCC:30:HV_SW
ca://fb:EM1K0:GMD:GCC:30:PRESS_RBV
ca://fb:EM1K0:GMD:GCC:30:STATE_RBV
ca://fb:EM1K0:GMD:GCC:30:ILK_OK_RBV
ca://fb:EM1K0:GMD:PTM:30:RUN_SW
ca://fb:EM1K0:GMD:PTM:30:STATE_RBV
ca://fb:EM1K0:GMD:PTM:30:FAULT_RBV
ca://fb:EM1K0:GMD:PTM:30:ILK_OK_RBV
ca://fb:EM1K0:GMD:GPI:40:PRESS_RBV
ca://fb:EM1K0:GMD:GPI:40:PRESS_OK_RBV
ca://fb:EM1K0:GMD:GCC:40:HV_SW
ca://fb:EM1K0:GMD:GCC:40:PRESS_RBV
ca://fb:EM1K0:GMD:GCC:40:STATE_RBV
ca://fb:EM1K0:GMD:GCC:40:ILK_OK_RBV
ca://fb:EM1K0:GMD:PTM:40:RUN_SW
ca://fb:EM1K0:GMD:PTM:40:STATE_RBV
ca://fb:EM1K0:GMD:PTM:40:FAULT_RBV
ca://fb:EM1K0:GMD:PTM:40:ILK_OK_RBV
ca://fb:EM1K0:GMD:PRT:40:RUN_SW
ca://fb:EM1K0:GMD:PRT:40:STATE_RBV
ca://fb:EM1K0:GMD:PRT:40:ERROR_RBV
ca://fb:EM1K0:GMD:PRT:40:ILK_OK_RBV
ca://fb:EM1K0:GMD:VRC:50:OPN_SW
ca://fb:EM1K0:GMD:VRC:50:OPN_DI_RBV
ca://fb:EM1K0:GMD:VRC:50:CLS_DI_RBV
ca://fb:EM1K0:GMD:VRC:50:STATE_RBV
ca://fb:EM1K0:GMD:VRC:50:OPN_OK_RBV
ca://fb:EM1K0:GMD:GCC:50:HV_SW
ca://fb:EM1K0:GMD:GCC:50:PRESS_RBV
ca://fb:EM1K0:GMD:GCC:50:STATE_RBV
ca://fb:EM1K0:GMD:GCC:50:ILK_OK_RBV
ca://fb:EM1K0:GMD:PTM:50:RUN_SW
ca://fb:EM1K0:GMD:PTM:50:STATE_RBV
ca://fb:EM1K0:GMD:PTM:50:FAULT_RBV
ca://fb:EM1K0:GMD:PTM:50:ILK_OK_RBV
ca://fb:EM1K0:GMD:VRC:60:OPN_SW
ca://fb:EM1K0:GMD:VRC:60:OPN_DI_RBV
ca://fb:EM1K0:GMD:VRC:60:CLS_DI_RBV
ca://fb:EM1K0:GMD:VRC:60:STATE_RBV
ca://fb:EM1K0:GMD:VRC:60:OPN_OK_RBV
ca://fb:EM1K0:GMD:GCC:60:HV_SW
ca://fb:EM1K0:GMD:GCC:60:PRESS_RBV
ca://fb:EM1K0:GMD:GCC:60:STATE_RBV
ca://fb:EM1K0:GMD:GCC:60:ILK_OK_RBV
ca://fb:EM1K0:GMD:PTM:60:RUN_SW
ca://fb:EM1K0:GMD:PTM:60:STATE_RBV
ca://fb:EM1K0:GMD:PTM:60:FAULT_RBV
ca://fb:EM1K0:GMD:PTM:60:ILK_OK_RBV
ca://fb:EM1K0:GMD:VRC:70:OPN_SW
ca://fb:EM1K0:GMD:VRC:70:OPN_DI_RBV
ca://fb:EM1K0:GMD:VRC:70:CLS_DI_RBV
ca://fb:EM1K0:GMD:VRC:70:STATE_RBV
ca://fb:EM1K0:GMD:VRC:70:OPN_OK_RBV
ca://fb:EM1K0:GMD:GPI:70:PRESS_RBV
ca://fb:EM1K0:GMD:GPI:70:PRESS_OK_RBV
ca://fb:EM1K0:GMD:GCC:70:HV_SW
ca://fb:EM1K0:GMD:GCC:70:PRESS_RBV
ca://fb:EM1K0:GMD:GCC:70:STATE_RBV
ca://fb:EM1K0:GMD:GCC:70:ILK_OK_RBV
ca://fb:EM1K0:GMD:PTM:70:RUN_SW
ca://fb:EM1K0:GMD:PTM:70:STATE_RBV
ca://fb:EM1K0:GMD:PTM:70:FAULT_RBV
ca://fb:EM1K0:GMD:PTM:70:ILK_OK_RBV

IOC pv list:
ioc-tst-ads> dbl
fb:EM1K0:GMD:GPI:10:HV_SW
fb:EM1K0:GMD:GPI:40:HV_SW
fb:EM1K0:GMD:GPI:70:HV_SW
fb:EM1K0:GMD:PTM:10:RUN_SW
fb:EM1K0:GMD:PTM:10:RST_SW
fb:EM1K0:GMD:PTM:20:RUN_SW
fb:EM1K0:GMD:PTM:20:RST_SW
fb:EM1K0:GMD:PTM:30:RUN_SW
fb:EM1K0:GMD:PTM:30:RST_SW
fb:EM1K0:GMD:PTM:40:RUN_SW
fb:EM1K0:GMD:PTM:40:RST_SW
fb:EM1K0:GMD:PTM:50:RUN_SW
fb:EM1K0:GMD:PTM:50:RST_SW
fb:EM1K0:GMD:PTM:60:RUN_SW
fb:EM1K0:GMD:PTM:60:RST_SW
fb:EM1K0:GMD:PTM:70:RUN_SW
fb:EM1K0:GMD:PTM:70:RST_SW
fb:EM1K0:GMD:VRC:10:OPN_SW
fb:EM1K0:GMD:VRC:10:FORCE_OPN
fb:EM1K0:GMD:VRC:20:OPN_SW
fb:EM1K0:GMD:VRC:20:FORCE_OPN
fb:EM1K0:GMD:VRC:30:OPN_SW
fb:EM1K0:GMD:VRC:30:FORCE_OPN
fb:EM1K0:GMD:VRC:50:OPN_SW
fb:EM1K0:GMD:VRC:50:FORCE_OPN
fb:EM1K0:GMD:VRC:60:OPN_SW
fb:EM1K0:GMD:VRC:60:FORCE_OPN
fb:EM1K0:GMD:VRC:70:OPN_SW
fb:EM1K0:GMD:VRC:70:FORCE_OPN
fb:EM1K0:GMD:GCC:10:HV_SW
fb:EM1K0:GMD:GCC:20:HV_SW
fb:EM1K0:GMD:GCC:30:HV_SW
fb:EM1K0:GMD:GCC:40:HV_SW
fb:EM1K0:GMD:GCC:50:HV_SW
fb:EM1K0:GMD:GCC:60:HV_SW
fb:EM1K0:GMD:GCC:70:HV_SW
fb:EM1K0:GMD:PRT:40:REMOTE
fb:EM1K0:GMD:GPI:10:VAC_SP
fb:EM1K0:GMD:GPI:10:PRO_SP
fb:EM1K0:GMD:GPI:10:SP_HYS
fb:EM1K0:GMD:GPI:40:VAC_SP
fb:EM1K0:GMD:GPI:40:PRO_SP
fb:EM1K0:GMD:GPI:40:SP_HYS
fb:EM1K0:GMD:GPI:70:VAC_SP
fb:EM1K0:GMD:GPI:70:PRO_SP
fb:EM1K0:GMD:GPI:70:SP_HYS
fb:EM1K0:GMD:PTM:10:BackingPressureSP
fb:EM1K0:GMD:PTM:10:InletPressureSP
fb:EM1K0:GMD:PTM:20:BackingPressureSP
fb:EM1K0:GMD:PTM:20:InletPressureSP
fb:EM1K0:GMD:PTM:30:BackingPressureSP
fb:EM1K0:GMD:PTM:30:InletPressureSP
fb:EM1K0:GMD:PTM:40:BackingPressureSP
fb:EM1K0:GMD:PTM:40:InletPressureSP
fb:EM1K0:GMD:PTM:50:BackingPressureSP
fb:EM1K0:GMD:PTM:50:InletPressureSP
fb:EM1K0:GMD:PTM:60:BackingPressureSP
fb:EM1K0:GMD:PTM:60:InletPressureSP
fb:EM1K0:GMD:PTM:70:BackingPressureSP
fb:EM1K0:GMD:PTM:70:InletPressureSP
fb:EM1K0:GMD:GCC:10:VAC_SP
fb:EM1K0:GMD:GCC:10:PRO_SP
fb:EM1K0:GMD:GCC:10:SP_HYS
fb:EM1K0:GMD:GCC:20:VAC_SP
fb:EM1K0:GMD:GCC:20:PRO_SP
fb:EM1K0:GMD:GCC:20:SP_HYS
fb:EM1K0:GMD:GCC:30:VAC_SP
fb:EM1K0:GMD:GCC:30:PRO_SP
fb:EM1K0:GMD:GCC:30:SP_HYS
fb:EM1K0:GMD:GCC:40:VAC_SP
fb:EM1K0:GMD:GCC:40:PRO_SP
fb:EM1K0:GMD:GCC:40:SP_HYS
fb:EM1K0:GMD:GCC:50:VAC_SP
fb:EM1K0:GMD:GCC:50:PRO_SP
fb:EM1K0:GMD:GCC:50:SP_HYS
fb:EM1K0:GMD:GCC:60:VAC_SP
fb:EM1K0:GMD:GCC:60:PRO_SP
fb:EM1K0:GMD:GCC:60:SP_HYS
fb:EM1K0:GMD:GCC:70:VAC_SP
fb:EM1K0:GMD:GCC:70:PRO_SP
fb:EM1K0:GMD:GCC:70:SP_HYS
plcInfo_RBV
plcLocalTime_RBV
simHeartbeat_RBV
plcHeartbeat_RBV
fb:EM1K0:GMD:GPI:10:PRESS_AI_RBV
fb:EM1K0:GMD:GPI:40:PRESS_AI_RBV
fb:EM1K0:GMD:GPI:70:PRESS_AI_RBV
fb:EM1K0:GMD:PTM:10:SPEED_RDBK_RBV
fb:EM1K0:GMD:PTM:10:Current_MON_RBV
fb:EM1K0:GMD:PTM:20:SPEED_RDBK_RBV
fb:EM1K0:GMD:PTM:20:Current_MON_RBV
fb:EM1K0:GMD:PTM:30:SPEED_RDBK_RBV
fb:EM1K0:GMD:PTM:30:Current_MON_RBV
fb:EM1K0:GMD:PTM:40:SPEED_RDBK_RBV
fb:EM1K0:GMD:PTM:40:Current_MON_RBV
fb:EM1K0:GMD:PTM:50:SPEED_RDBK_RBV
fb:EM1K0:GMD:PTM:50:Current_MON_RBV
fb:EM1K0:GMD:PTM:60:SPEED_RDBK_RBV
fb:EM1K0:GMD:PTM:60:Current_MON_RBV
fb:EM1K0:GMD:PTM:70:SPEED_RDBK_RBV
fb:EM1K0:GMD:PTM:70:Current_MON_RBV
fb:EM1K0:GMD:GCC:10:PRESS_AI_RBV
fb:EM1K0:GMD:GCC:20:PRESS_AI_RBV
fb:EM1K0:GMD:GCC:30:PRESS_AI_RBV
fb:EM1K0:GMD:GCC:40:PRESS_AI_RBV
fb:EM1K0:GMD:GCC:50:PRESS_AI_RBV
fb:EM1K0:GMD:GCC:60:PRESS_AI_RBV
fb:EM1K0:GMD:GCC:70:PRESS_AI_RBV
fb:EM1K0:GMD:GPI:10:AT_VAC_RBV
fb:EM1K0:GMD:GPI:10:PRESS_OK_RBV
fb:EM1K0:GMD:GPI:10:HV_SW_RBV
fb:EM1K0:GMD:GPI:10:HV_ON_RBV
fb:EM1K0:GMD:GPI:10:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GPI:10:HV_DIS_DO_RBV
fb:EM1K0:GMD:GPI:10:ILK_OK_RBV
fb:EM1K0:GMD:GPI:40:AT_VAC_RBV
fb:EM1K0:GMD:GPI:40:PRESS_OK_RBV
fb:EM1K0:GMD:GPI:40:HV_SW_RBV
fb:EM1K0:GMD:GPI:40:HV_ON_RBV
fb:EM1K0:GMD:GPI:40:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GPI:40:HV_DIS_DO_RBV
fb:EM1K0:GMD:GPI:40:ILK_OK_RBV
fb:EM1K0:GMD:GPI:70:AT_VAC_RBV
fb:EM1K0:GMD:GPI:70:PRESS_OK_RBV
fb:EM1K0:GMD:GPI:70:HV_SW_RBV
fb:EM1K0:GMD:GPI:70:HV_ON_RBV
fb:EM1K0:GMD:GPI:70:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GPI:70:HV_DIS_DO_RBV
fb:EM1K0:GMD:GPI:70:ILK_OK_RBV
fb:EM1K0:GMD:PTM:10:RUN_SW_RBV
fb:EM1K0:GMD:PTM:10:RST_SW_RBV
fb:EM1K0:GMD:PTM:10:RUN_DO_RBV
fb:EM1K0:GMD:PTM:10:ILK_OK_RBV
fb:EM1K0:GMD:PTM:10:ACCEL_RBV
fb:EM1K0:GMD:PTM:10:AT_SPD_RBV
fb:EM1K0:GMD:PTM:10:FAULT_RBV
fb:EM1K0:GMD:PTM:10:WARN_RBV
fb:EM1K0:GMD:PTM:10:ALARM_RBV
fb:EM1K0:GMD:PTM:20:RUN_SW_RBV
fb:EM1K0:GMD:PTM:20:RST_SW_RBV
fb:EM1K0:GMD:PTM:20:RUN_DO_RBV
fb:EM1K0:GMD:PTM:20:ILK_OK_RBV
fb:EM1K0:GMD:PTM:20:ACCEL_RBV
fb:EM1K0:GMD:PTM:20:AT_SPD_RBV
fb:EM1K0:GMD:PTM:20:FAULT_RBV
fb:EM1K0:GMD:PTM:20:WARN_RBV
fb:EM1K0:GMD:PTM:20:ALARM_RBV
fb:EM1K0:GMD:PTM:30:RUN_SW_RBV
fb:EM1K0:GMD:PTM:30:RST_SW_RBV
fb:EM1K0:GMD:PTM:30:RUN_DO_RBV
fb:EM1K0:GMD:PTM:30:ILK_OK_RBV
fb:EM1K0:GMD:PTM:30:ACCEL_RBV
fb:EM1K0:GMD:PTM:30:AT_SPD_RBV
fb:EM1K0:GMD:PTM:30:FAULT_RBV
fb:EM1K0:GMD:PTM:30:WARN_RBV
fb:EM1K0:GMD:PTM:30:ALARM_RBV
fb:EM1K0:GMD:PTM:40:RUN_SW_RBV
fb:EM1K0:GMD:PTM:40:RST_SW_RBV
fb:EM1K0:GMD:PTM:40:RUN_DO_RBV
fb:EM1K0:GMD:PTM:40:ILK_OK_RBV
fb:EM1K0:GMD:PTM:40:ACCEL_RBV
fb:EM1K0:GMD:PTM:40:AT_SPD_RBV
fb:EM1K0:GMD:PTM:40:FAULT_RBV
fb:EM1K0:GMD:PTM:40:WARN_RBV
fb:EM1K0:GMD:PTM:40:ALARM_RBV
fb:EM1K0:GMD:PTM:50:RUN_SW_RBV
fb:EM1K0:GMD:PTM:50:RST_SW_RBV
fb:EM1K0:GMD:PTM:50:RUN_DO_RBV
fb:EM1K0:GMD:PTM:50:ILK_OK_RBV
fb:EM1K0:GMD:PTM:50:ACCEL_RBV
fb:EM1K0:GMD:PTM:50:AT_SPD_RBV
fb:EM1K0:GMD:PTM:50:FAULT_RBV
fb:EM1K0:GMD:PTM:50:WARN_RBV
fb:EM1K0:GMD:PTM:50:ALARM_RBV
fb:EM1K0:GMD:PTM:60:RUN_SW_RBV
fb:EM1K0:GMD:PTM:60:RST_SW_RBV
fb:EM1K0:GMD:PTM:60:RUN_DO_RBV
fb:EM1K0:GMD:PTM:60:ILK_OK_RBV
fb:EM1K0:GMD:PTM:60:ACCEL_RBV
fb:EM1K0:GMD:PTM:60:AT_SPD_RBV
fb:EM1K0:GMD:PTM:60:FAULT_RBV
fb:EM1K0:GMD:PTM:60:WARN_RBV
fb:EM1K0:GMD:PTM:60:ALARM_RBV
fb:EM1K0:GMD:PTM:70:RUN_SW_RBV
fb:EM1K0:GMD:PTM:70:RST_SW_RBV
fb:EM1K0:GMD:PTM:70:RUN_DO_RBV
fb:EM1K0:GMD:PTM:70:ILK_OK_RBV
fb:EM1K0:GMD:PTM:70:ACCEL_RBV
fb:EM1K0:GMD:PTM:70:AT_SPD_RBV
fb:EM1K0:GMD:PTM:70:FAULT_RBV
fb:EM1K0:GMD:PTM:70:WARN_RBV
fb:EM1K0:GMD:PTM:70:ALARM_RBV
fb:EM1K0:GMD:VRC:10:OPN_DI_RBV
fb:EM1K0:GMD:VRC:10:CLS_DI_RBV
fb:EM1K0:GMD:VRC:10:OPN_SW_RBV
fb:EM1K0:GMD:VRC:10:FORCE_OPN_RBV
fb:EM1K0:GMD:VRC:10:OVRD_ON_RBV
fb:EM1K0:GMD:VRC:10:OPN_OK_RBV
fb:EM1K0:GMD:VRC:10:CLS_OK_RBV
fb:EM1K0:GMD:VRC:10:OPN_DO_RBV
fb:EM1K0:GMD:VRC:20:OPN_DI_RBV
fb:EM1K0:GMD:VRC:20:CLS_DI_RBV
fb:EM1K0:GMD:VRC:20:OPN_SW_RBV
fb:EM1K0:GMD:VRC:20:FORCE_OPN_RBV
fb:EM1K0:GMD:VRC:20:OVRD_ON_RBV
fb:EM1K0:GMD:VRC:20:OPN_OK_RBV
fb:EM1K0:GMD:VRC:20:CLS_OK_RBV
fb:EM1K0:GMD:VRC:20:OPN_DO_RBV
fb:EM1K0:GMD:VRC:30:OPN_DI_RBV
fb:EM1K0:GMD:VRC:30:CLS_DI_RBV
fb:EM1K0:GMD:VRC:30:OPN_SW_RBV
fb:EM1K0:GMD:VRC:30:FORCE_OPN_RBV
fb:EM1K0:GMD:VRC:30:OVRD_ON_RBV
fb:EM1K0:GMD:VRC:30:OPN_OK_RBV
fb:EM1K0:GMD:VRC:30:CLS_OK_RBV
fb:EM1K0:GMD:VRC:30:OPN_DO_RBV
fb:EM1K0:GMD:VRC:50:OPN_DI_RBV
fb:EM1K0:GMD:VRC:50:CLS_DI_RBV
fb:EM1K0:GMD:VRC:50:OPN_SW_RBV
fb:EM1K0:GMD:VRC:50:FORCE_OPN_RBV
fb:EM1K0:GMD:VRC:50:OVRD_ON_RBV
fb:EM1K0:GMD:VRC:50:OPN_OK_RBV
fb:EM1K0:GMD:VRC:50:CLS_OK_RBV
fb:EM1K0:GMD:VRC:50:OPN_DO_RBV
fb:EM1K0:GMD:VRC:60:OPN_DI_RBV
fb:EM1K0:GMD:VRC:60:CLS_DI_RBV
fb:EM1K0:GMD:VRC:60:OPN_SW_RBV
fb:EM1K0:GMD:VRC:60:FORCE_OPN_RBV
fb:EM1K0:GMD:VRC:60:OVRD_ON_RBV
fb:EM1K0:GMD:VRC:60:OPN_OK_RBV
fb:EM1K0:GMD:VRC:60:CLS_OK_RBV
fb:EM1K0:GMD:VRC:60:OPN_DO_RBV
fb:EM1K0:GMD:VRC:70:OPN_DI_RBV
fb:EM1K0:GMD:VRC:70:CLS_DI_RBV
fb:EM1K0:GMD:VRC:70:OPN_SW_RBV
fb:EM1K0:GMD:VRC:70:FORCE_OPN_RBV
fb:EM1K0:GMD:VRC:70:OVRD_ON_RBV
fb:EM1K0:GMD:VRC:70:OPN_OK_RBV
fb:EM1K0:GMD:VRC:70:CLS_OK_RBV
fb:EM1K0:GMD:VRC:70:OPN_DO_RBV
fb:EM1K0:GMD:GCC:10:AT_VAC_RBV
fb:EM1K0:GMD:GCC:10:PRESS_OK_RBV
fb:EM1K0:GMD:GCC:10:HV_SW_RBV
fb:EM1K0:GMD:GCC:10:HV_ON_RBV
fb:EM1K0:GMD:GCC:10:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GCC:10:HV_DIS_DO_RBV
fb:EM1K0:GMD:GCC:10:ILK_OK_RBV
fb:EM1K0:GMD:GCC:20:AT_VAC_RBV
fb:EM1K0:GMD:GCC:20:PRESS_OK_RBV
fb:EM1K0:GMD:GCC:20:HV_SW_RBV
fb:EM1K0:GMD:GCC:20:HV_ON_RBV
fb:EM1K0:GMD:GCC:20:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GCC:20:HV_DIS_DO_RBV
fb:EM1K0:GMD:GCC:20:ILK_OK_RBV
fb:EM1K0:GMD:GCC:30:AT_VAC_RBV
fb:EM1K0:GMD:GCC:30:PRESS_OK_RBV
fb:EM1K0:GMD:GCC:30:HV_SW_RBV
fb:EM1K0:GMD:GCC:30:HV_ON_RBV
fb:EM1K0:GMD:GCC:30:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GCC:30:HV_DIS_DO_RBV
fb:EM1K0:GMD:GCC:30:ILK_OK_RBV
fb:EM1K0:GMD:GCC:40:AT_VAC_RBV
fb:EM1K0:GMD:GCC:40:PRESS_OK_RBV
fb:EM1K0:GMD:GCC:40:HV_SW_RBV
fb:EM1K0:GMD:GCC:40:HV_ON_RBV
fb:EM1K0:GMD:GCC:40:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GCC:40:HV_DIS_DO_RBV
fb:EM1K0:GMD:GCC:40:ILK_OK_RBV
fb:EM1K0:GMD:GCC:50:AT_VAC_RBV
fb:EM1K0:GMD:GCC:50:PRESS_OK_RBV
fb:EM1K0:GMD:GCC:50:HV_SW_RBV
fb:EM1K0:GMD:GCC:50:HV_ON_RBV
fb:EM1K0:GMD:GCC:50:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GCC:50:HV_DIS_DO_RBV
fb:EM1K0:GMD:GCC:50:ILK_OK_RBV
fb:EM1K0:GMD:GCC:60:AT_VAC_RBV
fb:EM1K0:GMD:GCC:60:PRESS_OK_RBV
fb:EM1K0:GMD:GCC:60:HV_SW_RBV
fb:EM1K0:GMD:GCC:60:HV_ON_RBV
fb:EM1K0:GMD:GCC:60:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GCC:60:HV_DIS_DO_RBV
fb:EM1K0:GMD:GCC:60:ILK_OK_RBV
fb:EM1K0:GMD:GCC:70:AT_VAC_RBV
fb:EM1K0:GMD:GCC:70:PRESS_OK_RBV
fb:EM1K0:GMD:GCC:70:HV_SW_RBV
fb:EM1K0:GMD:GCC:70:HV_ON_RBV
fb:EM1K0:GMD:GCC:70:DISC_ACTIVE_RBV
fb:EM1K0:GMD:GCC:70:HV_DIS_DO_RBV
fb:EM1K0:GMD:GCC:70:ILK_OK_RBV
fb:EM1K0:GMD:PRT:40:REMOTE_RBV
fb:EM1K0:GMD:PRT:40:ALARM_OK_RBV
fb:EM1K0:GMD:PRT:40:RUN_DI_RBV
fb:EM1K0:GMD:GPI:10:PRESS_RBV
fb:EM1K0:GMD:GPI:10:VAC_SP_RBV
fb:EM1K0:GMD:GPI:10:PRO_SP_RBV
fb:EM1K0:GMD:GPI:10:SP_HYS_RBV
fb:EM1K0:GMD:GPI:40:PRESS_RBV
fb:EM1K0:GMD:GPI:40:VAC_SP_RBV
fb:EM1K0:GMD:GPI:40:PRO_SP_RBV
fb:EM1K0:GMD:GPI:40:SP_HYS_RBV
fb:EM1K0:GMD:GPI:70:PRESS_RBV
fb:EM1K0:GMD:GPI:70:VAC_SP_RBV
fb:EM1K0:GMD:GPI:70:PRO_SP_RBV
fb:EM1K0:GMD:GPI:70:SP_HYS_RBV
fb:EM1K0:GMD:PTM:10:BackingPressureSP_RBV
fb:EM1K0:GMD:PTM:10:InletPressureSP_RBV
fb:EM1K0:GMD:PTM:20:BackingPressureSP_RBV
fb:EM1K0:GMD:PTM:20:InletPressureSP_RBV
fb:EM1K0:GMD:PTM:30:BackingPressureSP_RBV
fb:EM1K0:GMD:PTM:30:InletPressureSP_RBV
fb:EM1K0:GMD:PTM:40:BackingPressureSP_RBV
fb:EM1K0:GMD:PTM:40:InletPressureSP_RBV
fb:EM1K0:GMD:PTM:50:BackingPressureSP_RBV
fb:EM1K0:GMD:PTM:50:InletPressureSP_RBV
fb:EM1K0:GMD:PTM:60:BackingPressureSP_RBV
fb:EM1K0:GMD:PTM:60:InletPressureSP_RBV
fb:EM1K0:GMD:PTM:70:BackingPressureSP_RBV
fb:EM1K0:GMD:PTM:70:InletPressureSP_RBV
fb:EM1K0:GMD:GCC:10:PRESS_RBV
fb:EM1K0:GMD:GCC:10:VAC_SP_RBV
fb:EM1K0:GMD:GCC:10:PRO_SP_RBV
fb:EM1K0:GMD:GCC:10:SP_HYS_RBV
fb:EM1K0:GMD:GCC:20:PRESS_RBV
fb:EM1K0:GMD:GCC:20:VAC_SP_RBV
fb:EM1K0:GMD:GCC:20:PRO_SP_RBV
fb:EM1K0:GMD:GCC:20:SP_HYS_RBV
fb:EM1K0:GMD:GCC:30:PRESS_RBV
fb:EM1K0:GMD:GCC:30:VAC_SP_RBV
fb:EM1K0:GMD:GCC:30:PRO_SP_RBV
fb:EM1K0:GMD:GCC:30:SP_HYS_RBV
fb:EM1K0:GMD:GCC:40:PRESS_RBV
fb:EM1K0:GMD:GCC:40:VAC_SP_RBV
fb:EM1K0:GMD:GCC:40:PRO_SP_RBV
fb:EM1K0:GMD:GCC:40:SP_HYS_RBV
fb:EM1K0:GMD:GCC:50:PRESS_RBV
fb:EM1K0:GMD:GCC:50:VAC_SP_RBV
fb:EM1K0:GMD:GCC:50:PRO_SP_RBV
fb:EM1K0:GMD:GCC:50:SP_HYS_RBV
fb:EM1K0:GMD:GCC:60:PRESS_RBV
fb:EM1K0:GMD:GCC:60:VAC_SP_RBV
fb:EM1K0:GMD:GCC:60:PRO_SP_RBV
fb:EM1K0:GMD:GCC:60:SP_HYS_RBV
fb:EM1K0:GMD:GCC:70:PRESS_RBV
fb:EM1K0:GMD:GCC:70:VAC_SP_RBV
fb:EM1K0:GMD:GCC:70:PRO_SP_RBV
fb:EM1K0:GMD:GCC:70:SP_HYS_RBV
