### ISSUE TITLE
Expert Screens:  Middle Click Channel Access PVs and Updating Pressure Readings.

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/pcdswidgets#30]
## Expected Behavior

Can the middle click that shows the Channel Access PV show up on the expert screens as well? Also the pressure readings on the main screen does not show up on the expert screens 

## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

![image](https://user-images.githubusercontent.com/42284230/75124092-cbd87b00-5661-11ea-8f39-b24e7702da35.png)

**Comment by hhslepicka** [comment]
Thanks @slacAdpai For the issue.
@klauer and I identified this issue late Friday and we are thinking about possible solutions. Typhos has no metadata to select Exponential format and that is why you see the 0. It will be fixed soon.

About the middle click, do you mean when you middle click at a value at the expert screen?

**Comment by slacAdpai** [comment]
Hello Hugo,

Thanks for the update about readback displays.

For the middle click, it is for the right column on the expert screens.

Cheers,
Allen

**Comment by hhslepicka** [comment]
@slacAdpai about the middle click, I just tested it here using the dev environment and all seems fine.
Would you mind to stop by and we can check it together?

**Comment by hhslepicka** [comment]
Job Done! It is now available via `dev_conda`.
The middle click was tested and it is working properly.
![Screen Shot 2020-02-24 at 2 11 01 PM](https://user-images.githubusercontent.com/8185425/75195816-883c4a80-570f-11ea-81b9-fb2a3362a00f.png)
