### ISSUE TITLE
Pirani/Rough gauge widget state pv

### ISSUE THREAD

**Issue by ghalym** [pcdshub/pcdswidgets#43]
Initially it was agreed that this widget state pv is :PRESS_OK_RBV. All other widgets read STATE_RBV, making this the odd one out.
Can we change the state of the widget to be linked to the STATE_RBV instead? 
I understand we will need to update the stylesheets accordingly, but will it have any other effect?

**Comment by hhslepicka** [comment]
State is very straightforward. You will only need to adjust the stylesheets if the enum strings changed between one PV and the other... otherwise not even that is required. Knowing that, should I move forward with the change?

**Comment by ghalym** [comment]
Yes please. Thank you for the quick response.
