### ISSUE TITLE
Adding Color to FastShutter Widget's arrow section (aka inverted christmas tree)

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/pcdswidgets#46]
![20200625_153833](https://user-images.githubusercontent.com/42284230/85804836-81463880-b6ff-11ea-81c6-be9a7b9da642.jpg)

## Expected Behavior
Being able to color the arrow section of the FSV would allow the error status to show up on the FSV. This functionality would be similar to the functionality of the VGC icon.

## Current Behavior
Currently there is no color on the FSV arrows

## Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by klauer** [comment]
Roughly equivalent: 🌷 
 \</kidding>

**Comment by slacAdpai** [comment]
Now that's a real pretty looker!
