### ISSUE TITLE
Fast Shutter widget changes

### ISSUE THREAD

**Issue by ghalym** [pcdshub/pcdswidgets#48]
## Expected Behavior
1 - In order to be consistent with the pneumatic valves it should be linked to STATE_RBV  _error_suffix = ":STATE_RBV"  .
2 - Need to add one more command pv. Fast shutter has two commands OPN_SW and CLS_SW, 

## Current Behavior
1 - The fast shutter  _error_suffix = ":ERROR_RBV".
2 - _command_suffix = ":OPN_SW"

## Possible Solution
1 -  _error_suffix = ":STATE_RBV"  
2- Is is possible to link the command to two pvs?

**Comment by hhslepicka** [comment]
@ghalym is this just for the fast valve?
Also, how should the two commands work?
Are they both write 1 to open and close?

Could the OPN_SW be transformed in a pv in which 0 closes it and 1 opens and become an ENUM like for others?

**Comment by ghalym** [comment]
@hhslepicka yes, only for the fast shutter.
The fast shutter is a double acting solenoid, It reads OPN_SW to actuate the valve open, then CLS_SW to actuate the valve to close. It is different from the other valves.
Can we have two separate command buttons, linked to two command pvs?

**Comment by hhslepicka** [comment]
@ghalym no problem. I will get going on it.

**Comment by ghalym** [comment]
Thanks!
