### ISSUE TITLE
After the update to VFS in pcdsdevices and also to FastShutter ind pcdswidgets, Objects not loading properly

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/pcdswidgets#50]
Expert screens are not loading properly.

## Current Behavior
![image](https://user-images.githubusercontent.com/42284230/86136284-be644f00-baa0-11ea-87aa-c18d9e4b7d73.png)

`  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdswidgets/vacuum/base.py", line 428, in _handle_icon_click
    display = typhos.TyphosDeviceDisplay.from_class(klass, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/typhos/display.py", line 1121, in from_class
    'device %s', obj)`

## Steps to Reproduce (for bugs)

1. Open HXR Beamline Vacuum
2. Click on a VGC or VFS icon. It cannot bring up the expert screen. There is an UnboundedLocalError
3.

**Comment by hhslepicka** [comment]
That was due to the update that you executed yesterday at night at pcdsdevices. It introduced a new dependency which was not installed yet ("schema"). Zach installed it this morning and it should be good now.
Please test again and report back here.

**Comment by slacAdpai** [comment]
Was schema merged into the repo but not pulled to the working local copy for lucid?

**Comment by hhslepicka** [comment]
It was a new external dependency of pcdsdevices.
