### ISSUE TITLE
More VFS (green/red) Fire!!!! Please!

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/pcdswidgets#52]
## Expected Behavior

![image](https://user-images.githubusercontent.com/42284230/87504096-acdf8300-c61a-11ea-88ca-0d03d67916a5.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/42284230/87504007-730e7c80-c61a-11ea-8726-1fae039b8cfb.png)

## Possible Solution

Rwar! More Fire!!! hehehe!
![image](https://user-images.githubusercontent.com/42284230/87504164-d4365000-c61a-11ea-8f1e-8e8ba46152cf.png)

## Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by slacAdpai** [comment]
Hello Hugo, 
Is it possible to have a larger inverted christmas tree/fireball? I currently have the line width to 1 so some color can be seen. If the width is set to two, there are two specks of color left. I could barely see the color.
-Allen

**Comment by hhslepicka** [comment]
@slacAdpai donyou mean make the color area bigger or also make the arrow (black lines) bigger?
I can work on that some time tomorrow.

**Comment by slacAdpai** [comment]
Can both the color area and the arrow area (not line widths though) get bigger.

**Comment by hhslepicka** [comment]
Line Widths usually will come from stylesheet. I will get this one going and contact you over SLACK for input.
