### ISSUE TITLE
New Widget Pneumatic Valve with Readback Normally Open

### ISSUE THREAD

**Issue by ghalym** [pcdshub/pcdswidgets#59]
TMO has pneumatic valves installed that are normally open with limits switch readback, and we need a new widget for them.
## Expected Behavior
The behavior of this widget is similar to the that of a pneumatic valve. The difference is that it is commanded to close instead of commanded to open.
![image](https://user-images.githubusercontent.com/43865116/99571161-c6f1ef00-2987-11eb-8ddc-d233e53683dc.png)

**Comment by hhslepicka** [comment]
@ghalym about the icon, should we reuse an icon that is already there or do we need to develop a custom one for this widget?

**Comment by jyin999** [comment]
I prefer to use the same VGC icon.

**Comment by ghalym** [comment]
@jyin999 how about we add the letters NO next to t he top rectangle?

**Comment by jyin999** [comment]
@ghalym I like it.

**Comment by jyin999** [comment]
@hhslepicka any update?

**Comment by hhslepicka** [comment]
@jyin999 I am on vacation. I can work on it early January.

**Comment by jyin999** [comment]
@hhslepicka Early January is good. Thank you.  Have a great holiday time!

**Comment by hhslepicka** [comment]
@jyin999 and @ghalym does this look like what you are looking for?
![image](https://user-images.githubusercontent.com/8185425/103568042-b6cf9980-4e79-11eb-8284-69c64434fe00.png)

**Comment by jyin999** [comment]
@hhslepicka @ghalym Good for me.
