### ISSUE TITLE
Can't install from pypi

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdswidgets#79]
## Expected Behavior

pip install pcdswidgets should work

## Current Behavior

requirements.txt is read during setup.py but is not included in the distribution
```
Collecting pcdswidgets
  Downloading pcdswidgets-0.7.1.tar.gz (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 3.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qzzep_p7/pcdswidgets_0ff2413a26f349cf87dc0822c88e4b64/setup.py", line 5, in <module>
          with open('requirements.txt') as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

## Possible Solution

Do the full repo update we've been doing elsewhere incl switching away from setup.py

## Context
Experimenting with creating py3.11 environments with designer plugin support

**Comment by klauer** [comment]
I don't think I've been adding `requirements.txt` (or `dev-` / `docs-`) to `MANIFEST.in` in the recent migration. Either we already have it, or it's unnecessary with `pyproject.toml`... Need to double-check those repositories.

**Comment by ZLLentz** [comment]
Right, if the requirements are embedded in the toml file those repos are probably fine, otherwise they probably have this same issue
